secret:
  root_user_password: 'Server_Root_Password'
  mysql57_root_password: 'MySQL_Root_password'

  firewalld_service:
    - service: 'http'
      zone: 'public'
      permanent: 'yes'
      state: 'enabled'
      immediate: true
    - service: 'https'
      zone: 'public'
      permanent: 'yes'
      state: 'enabled'
      immediate: true
    - service: 'ssh'
      zone: 'public'
      permanent: 'yes'
      state: 'enabled'
      immediate: true
    - service: 'smtp'
      zone: 'public'
      permanent: 'yes'
      state: 'enabled'
      immediate: true

  firewalld_rich_rules:
    - port: "{{ sshd_port }}"
      protocol: tcp
      control: accept
      ips:
        - 111.222.333.xxx # Allow IP for sshd

