secret:
  ansible_users:
    - name: 'ansible'
      groups: 'wheel'
      append: 'yes'
      state: 'present'
      remove: 'no'
      password: "ansible"
      public_key: "~/.ssh/ansible_rsa.pub"
      login_shell: '/bin/bash'
      create_home: 'yes'
      sudo: 'present'
      comment: 'ansible user'
      expires: '-1'

  # users
  users:
    webuser:
      name: 'develop_001'
      groups: 'wheel,manager'
      append: 'yes'
      state: 'present'
      remove: 'no'
      password: "password"
      public_key: "~/.ssh/ansible_rsa.pub"
      login_shell: '/bin/bash'
      create_home: 'yes'
      sudo: 'absent'
      comment: 'vh1 comment'
      expires: '-1'
      docker_group: true

  # groups
  user_groups:
    wheel:
      name: 'wheel'
      state: 'present'
    manager:
      name: 'manager'
      state: 'present'

  ca_CN: "{{ httpd_domain }}"
  #countryName
  ca_C: JP
  #emailAddress
  ca_EMail: your_mailaddress
  #localityName
  ca_L:  your_locale
  #organizationName
  ca_O: your_organization
  #organizationalUnitName
  ca_OU: your_unit

  #stateOrProvinceName
  ca_ST: Tokyo

  postfix:
    smtp_host: "smtp_host" # Change
    smtp_port: "587" # Change
    smtp_user: "Account" # Change
    smtp_password: "password" # Change
    smtp_myhostname: "mailserver_hostname" # Change
    smtp_mydomain: "domain" # Change
    smtp_inet_interfaces: "localhost"
    smtp_inet_protocols: "ipv4"
