---
php:
  versions:
    php71: '7.1'
    php72: '7.2'
    php73: '7.3'
  language: 'Japanese'
  internal_encoding: 'UTF-8'
  encoding_translation: 'Off'
  detect_order: 'auto'
  filesize: '128M'
  timezone: 'Asia/Tokyo'

php_version: "{{ php.versions.php73 }}"

php_dependencies:
  - php
  - php-devel
  - php-mbstring
  - php-pdo
  - php-gd
  - php-xml
  - php-mcrypt
  - php-fpm
  - php-enchant
  - php-IDNA_Convert
  - php-mbstring
  - php-mysql
  - php-PHPMailer
  - php-process
  - php-simplepie
  - php-xml

remi_url: 'http://rpms.famillecollet.com/enterprise/remi-release-7.rpm'

