secret:
  root_user_password: 'vagrant'
  mysql57_root_password: 'root'

  firewalld_service:
    - service: 'http'
      zone: 'public'
      permanent: 'yes'
      state: 'enabled'
      immediate: true
    - service: 'https'
      zone: 'public'
      permanent: 'yes'
      state: 'enabled'
      immediate: true
    - service: 'ssh'
      zone: 'public'
      permanent: 'yes'
      state: 'enabled'
      immediate: true
    - service: 'smtp'
      zone: 'public'
      permanent: 'yes'
      state: 'enabled'
      immediate: true
      
  firewalld_rich_rules:
    - port: "{{ sshd_port }}"
      protocol: tcp
      control: accept
      ips:
        - 192.168.33.1 # allow IP for sshd
        - 192.168.33.55
