---

- name: check installed certbot
  become: true
  stat:
    path: "/usr/local/bin/certbot-auto"
  register: chk_certbot
  changed_when: False
  ignore_errors: yes

- name: Install certbot
  become: true
  get_url:
    url: "https://dl.eff.org/certbot-auto"
    dest: "/usr/local/bin/"
    mode: 755
  when: chk_certbot.stat.exists == false

